[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
taxi_park = "3i1YDj1ZKCypwoYqP21CzGatdPMzuRPUGrsjSxGBEp1Z"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/taxi-devnet-deployer.json"

[scripts]
test = "cargo test -p taxi-park"
