[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
taxi_park = "H7X7Ky8q6mvEdeDLikx6fPGAyjjHywR74W53DyXZJrsY"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/taxi-devnet-deployer.json"

[scripts]
test = "cargo test -p taxi-park"
