[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
taxi_park = "9ZLAzKr2taQMXPZjkAFDNfWHrtrCTspR7sXV1E2F6eVv"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/taxi-devnet-deployer.json"

[scripts]
test = "cargo test -p taxi-park"
