server {
    listen 80;
    listen [::]:80;
    server_name city.monosoftware.dev;
    return 301 https://city.monosoftware.dev$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name city.monosoftware.dev;
    ssl_certificate /etc/letsencrypt/live/monosoftware-wildcard/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/monosoftware-wildcard/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/taxi-city/current;
    index city.html;
    add_header X-Content-Type-Options nosniff always;

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
        add_header X-Content-Type-Options nosniff always;
    }
    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
        add_header X-Content-Type-Options nosniff always;
    }
}
